'use strict';
const test = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const { cssColorToHex } = require('../core/color');
const tokens = require('../core/tokens');
const check = require('../core/check');
const snapshot = require('../core/snapshot');
const swift = require('../adapters/swift');
const { loadConfig } = require('../core/config');

const FIX = path.join(__dirname, 'fixtures');
const BIN = path.join(__dirname, '..', 'bin', 'figma-code-sync.js');

/** A throwaway copy of a fixture, so tests can write. */
function scratch(name) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fcs-'));
  fs.cpSync(path.join(FIX, name), dir, { recursive: true });
  return dir;
}

test('colour: oklch, hex, rgb, alpha', () => {
  assert.equal(cssColorToHex('oklch(1 0 0)'), '#ffffff');
  assert.equal(cssColorToHex('oklch(0 0 0)'), '#000000');
  assert.equal(cssColorToHex('oklch(1 0 0 / 10%)'), '#ffffff1a');
  assert.equal(cssColorToHex('oklch(0.666 0.157 58.318)'), '#d97708'); // amber-600 round-tripped through oklch
  assert.equal(cssColorToHex('#ABC'), '#aabbcc');
  assert.equal(cssColorToHex('#d97706ff'), '#d97706');
  assert.equal(cssColorToHex('rgb(217, 119, 6)'), '#d97706');
  assert.equal(cssColorToHex('var(--x)'), null);
});

test('css-tailwind4: modes, brand override, radii, fonts — and a deterministic file', () => {
  const dir = scratch('web');
  const config = loadConfig(dir);
  const { text, errors } = tokens.build(config);
  assert.deepEqual(errors, []);
  const doc = JSON.parse(text);
  assert.equal(doc.color.primary.$value, '#d97706');
  assert.equal(doc.color.primary.$extensions.modes.dark, '#d97706', 'the later `:root, .dark` block wins in both modes');
  assert.equal(doc.color.background.$extensions.modes.dark, '#000000');
  assert.equal(doc.color.border.$extensions.modes.dark, '#ffffff1a');
  assert.equal(doc.color.primary.$extensions.web.var, 'var(--primary)');
  assert.equal(doc.radius.lg.$value, '8px');
  assert.equal(doc.radius.sm.$value, '4px');
  assert.equal(doc.font.sans.$extensions.figma.family, 'Inter');
  assert.equal(tokens.build(config).text, text);
  // freshness: missing → stale; written → fresh; source edited → stale
  assert.equal(tokens.check(config).fresh, false);
  tokens.write(config);
  assert.equal(tokens.check(config).fresh, true);
  const css = path.join(dir, 'src/theme.css');
  fs.writeFileSync(css, fs.readFileSync(css, 'utf8').replace('#d97706', '#b45309'));
  assert.equal(tokens.check(config).fresh, false);
});

test('swift: keeps file key order (integer-like keys included)', () => {
  const out = swift.render(fs.readFileSync(path.join(FIX, 'order-tokens.json'), 'utf8'), { sha256: 'abc' });
  assert.ok(out.indexOf('navy900') < out.indexOf('navy700'), 'file order, not numeric order');
  assert.match(out, /static let textPrimary = navy900/);
  assert.match(out, /static let bodyM = TextStyle\(family: \.ui, weight: \.regular, size: 16\)/);
  assert.match(out, /^\/\/ Generated by figma-code-sync tokens from design\/tokens.json \(sha256: abc\)/);
});

test('swift: a metric without a Swift name is an error', () => {
  const t = { palette: {}, color: {}, spacing: { md: { $type: 'spacing', $value: 16 } }, 'font-family': {}, type: {} };
  assert.throws(() => swift.render(t), /metric needs/);
});

test('check: clean fixture passes; roster and snapshot drift are caught', () => {
  const dir = scratch('web');
  const config = loadConfig(dir);
  tokens.write(config);
  const roster = { Button: { file: 'src/button.jsx', props: { variant: ['default', 'outline'] } } };
  assert.deepEqual(check.run(config, { roster, iconKeys: ['plus'] }).errors, []);

  const r2 = check.run(config, { roster: { Button: { props: { variant: ['default', 'outline', 'ghost'] } } } });
  assert.ok(r2.errors.some((e) => /variant="ghost" exists in code/.test(e)), r2.errors.join('\n'));

  const snap = path.join(dir, 'design/figma-components.json');
  const s = JSON.parse(fs.readFileSync(snap, 'utf8'));
  s.components[0].axes.Variant.push('link');
  s.components.push({ name: 'Icon/minus' });
  fs.writeFileSync(snap, JSON.stringify(s));
  const r3 = check.run(config);
  assert.ok(r3.errors.some((e) => /Variant=link is not mapped/.test(e)), r3.errors.join('\n'));
  assert.ok(r3.errors.some((e) => /Icon\/minus/.test(e)), r3.errors.join('\n'));
});

test('check: a missing export is an error; pending debts warn', () => {
  const dir = scratch('web');
  const config = loadConfig(dir);
  tokens.write(config);
  const mapPath = path.join(dir, 'design/component-map.json');
  const m = JSON.parse(fs.readFileSync(mapPath, 'utf8'));
  m.components.push({ id: 'Ghost', figma: null, pending: 'not drawn yet', code: { symbol: 'Ghost', file: 'src/button.jsx' } });
  fs.writeFileSync(mapPath, JSON.stringify(m));
  const r = check.run(config);
  assert.ok(r.errors.some((e) => /Ghost is not exported/.test(e)), r.errors.join('\n'));
  assert.ok(r.warnings.some((w) => /awaits a Figma component — not drawn yet/.test(w)));
});

test('check: Swift-era map entries (swift.symbol / swift.pending) are understood', () => {
  const dir = scratch('web');
  const config = loadConfig(dir);
  tokens.write(config);
  const mapPath = path.join(dir, 'design/component-map.json');
  const m = JSON.parse(fs.readFileSync(mapPath, 'utf8'));
  m.components[0].swift = m.components[0].code;
  delete m.components[0].code;
  m.components.push({ id: 'Later', figma: null, pending: 'later', swift: { symbol: 'Later', pending: 'not built' } });
  fs.writeFileSync(mapPath, JSON.stringify(m));
  const r = check.run(config);
  assert.deepEqual(r.errors, []);
  assert.ok(r.warnings.some((w) => /Later awaits its code — not built/.test(w)));
});

test('gate: additive vs breaking', () => {
  const base = { axes: { Variant: ['a', 'b'] }, properties: { Label: 'TEXT' }, shape: { pad: [0, 8, 0, 8], hash: 'x' } };
  assert.equal(snapshot.isAdditive(base, { ...base, axes: { Variant: ['a', 'b', 'c'] } }, 'changed'), true);
  assert.equal(snapshot.isAdditive(base, { ...base, axes: { Variant: ['a'] } }, 'changed'), false);
  assert.equal(snapshot.isAdditive(base, { ...base, properties: { Label: 'BOOLEAN' } }, 'changed'), false);
  assert.equal(snapshot.isAdditive(base, { ...base, shape: { pad: [0, 12, 0, 12], hash: 'y' } }, 'changed'), false);
  assert.deepEqual(snapshot.describe(base, { ...base, axes: { Variant: ['a', 'c'] } }), ['axis Variant +c -b']);
});

test('gate: a waiver must name each component, as a whole word', () => {
  const f = path.join(os.tmpdir(), `fcs-msg-${process.pid}`);
  const ack = (msg, names) => {
    fs.writeFileSync(f, msg);
    return snapshot.acknowledgement(os.tmpdir(), names, f).named;
  };
  const quiet = console.error;
  console.error = () => {};
  try {
    assert.deepEqual(ack('x\n\nDesign-drift: Button — padding only', ['Button']), ['Button']);
    assert.deepEqual(ack('how Design-drift: lines work', ['Button']), []);
    assert.deepEqual(ack('Design-drift: IconButton — radius', ['Button']), []);
  } finally {
    console.error = quiet;
    fs.unlinkSync(f);
  }
});

test('gate: usage counts call sites, minus declarations', () => {
  const dir = scratch('web');
  const config = loadConfig(dir);
  const cmap = { components: [{ figma: { component: 'Button' }, code: { symbol: 'Button' } }] };
  assert.equal(snapshot.codeUsage(config, cmap).Button, 2);
  const swiftish = { ...config, usage: { roots: ['src'], extensions: ['.jsx'], pattern: String.raw`\b{sym}\b`, declPattern: String.raw`^export function {sym}\b` } };
  // `\bButton\b`: the declaration, the import, two opening tags and one closing tag = 5 hits, minus 1 declaration
  assert.equal(snapshot.codeUsage(swiftish, cmap).Button, 4);
});

test('shapeOf: layout fingerprint and unbound paints', () => {
  const node = {
    type: 'COMPONENT', name: 'X', paddingTop: 4, paddingRight: 8, paddingBottom: 4, paddingLeft: 8, itemSpacing: 6,
    fills: [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }],
    strokes: [{ type: 'SOLID', color: { r: 0, g: 0, b: 0 }, boundVariables: { color: { id: 'V:1' } } }],
    strokeAlign: 'INSIDE', strokeWeight: 1,
  };
  const s = snapshot.shapeOf(node);
  assert.deepEqual([s.pad, s.gap, s.unbound, s.strokes], [[4, 8, 4, 8], 6, 1, { X: 'INSIDE/1' }]);
  assert.notEqual(snapshot.shapeOf({ ...node, paddingLeft: 12 }).hash, s.hash);
});

test('cli: init scaffolds without clobbering, and the scaffold generates cleanly', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fcs-init-'));
  const run = (...a) => execFileSync(process.execPath, [BIN, ...a], { cwd: dir, encoding: 'utf8' });
  run('init', '--adapter', 'swift');
  for (const f of ['figma-sync.config.js', 'design/component-map.json', 'design/figma-components.json', 'design/WORKFLOW.md', 'design/tokens.json', 'scripts/githooks/commit-msg', '.github/workflows/design-sync.yml']) {
    assert.ok(fs.existsSync(path.join(dir, f)), f);
  }
  fs.writeFileSync(path.join(dir, 'design/WORKFLOW.md'), 'mine');
  assert.match(run('init', '--adapter', 'swift'), /kept\s+design\/WORKFLOW.md/);
  assert.equal(fs.readFileSync(path.join(dir, 'design/WORKFLOW.md'), 'utf8'), 'mine');
  run('tokens');
  assert.equal(run('tokens', '--check'), '');
  assert.match(fs.readFileSync(path.join(dir, 'App/Theme+Generated.swift'), 'utf8'), /static let textPrimary = ink900/);
});

test('css-tailwind4: follows var() aliases between custom properties', () => {
  const dir = scratch('web');
  const css = path.join(dir, 'src/theme.css');
  fs.writeFileSync(css, fs.readFileSync(css, 'utf8')
    .replace('--color-border: var(--border);', '--color-border: var(--border);\n  --color-ring: var(--ring);')
    .replace('--radius: 0.5rem;', '--radius: 0.5rem;\n  --ring: var(--primary);'));
  const doc = JSON.parse(tokens.build(loadConfig(dir)).text);
  assert.equal(doc.color.ring.$value, '#d97706', 'ring → var(--primary) → the brand override');
});

test('gate: a snapshot in another fingerprint format is compared without its hashes', () => {
  const prev = { name: 'X', shape: { pad: [0, 8, 0, 8], gap: 4, strokes: {}, unbound: 0, hash: 'python-hash' } };
  const now = { name: 'X', shape: { pad: [0, 8, 0, 8], gap: 4, strokes: {}, unbound: 0, hash: 'js-hash' } };
  assert.equal(snapshot.isAdditive(prev, now, 'changed'), false, 'same format: a hash change is a change');
  const legacy = true;
  assert.equal(snapshot.isAdditive(snapshot.comparable(prev, legacy), snapshot.comparable(now, legacy), 'changed'), true);
  const moved = { ...now, shape: { ...now.shape, pad: [0, 12, 0, 12] } };
  assert.equal(snapshot.isAdditive(snapshot.comparable(prev, legacy), snapshot.comparable(moved, legacy), 'changed'), false, 'padding still gates');
});

test('css-tailwind4: publishes the spacing scale from --spacing, with p-N code syntax', () => {
  const dir = scratch('web');
  const cfgPath = path.join(dir, 'figma-sync.config.js');
  fs.writeFileSync(cfgPath, fs.readFileSync(cfgPath, 'utf8').replace("figmaFonts: { 'Inter Variable': 'Inter' }", "figmaFonts: { 'Inter Variable': 'Inter' }, spacing: { steps: [0.5, 1, 3, 24] }"));
  delete require.cache[require.resolve(cfgPath)];
  const doc = JSON.parse(tokens.build(loadConfig(dir)).text);
  assert.equal(doc.spacing['0-5'].$value, '2px', 'half steps are named with a dash: neither DTCG nor Figma allows "."');
  assert.equal(doc.spacing['3'].$value, '12px');
  assert.equal(doc.spacing['24'].$value, '96px');
  assert.equal(doc.spacing['3'].$extensions.web.var, 'calc(var(--spacing) * 3)');
  assert.equal(doc.spacing['3'].$extensions.figma.name, 'spacing/3');
});

test('css-tailwind4: asking for spacing without declaring --spacing is an error, not a guess', () => {
  const dir = scratch('web');
  const css = path.join(dir, 'src/theme.css');
  fs.writeFileSync(css, fs.readFileSync(css, 'utf8').replace(/@theme \{\s*--spacing: 0\.25rem;\s*\}\s*/, ''));
  const cfgPath = path.join(dir, 'figma-sync.config.js');
  fs.writeFileSync(cfgPath, fs.readFileSync(cfgPath, 'utf8').replace("figmaFonts: { 'Inter Variable': 'Inter' }", "figmaFonts: { 'Inter Variable': 'Inter' }, spacing: { steps: [1] }"));
  delete require.cache[require.resolve(cfgPath)];
  const { errors } = tokens.build(loadConfig(dir));
  assert.ok(errors.some((e) => /declares --spacing/.test(e)), errors.join('\n'));
});
